apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ftaovl5tb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ftaovl5tb-go 
  name: ftaovl5tb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ftaovl5tb-go 
